### ISSUE TITLE
Define models needed for command line script

### ISSUE THREAD

**Issue by dexter2206** [iitis/PyQBench#24]
We agreed that the command line script will accept YAML files as inputs and produce a YAML string as output. The validation of inputs and outputs, as well as serialization/deserialization, will be handled by [pydantic](https://pydantic-docs.helpmanual.io/).

We need to define the following models:

- model describing the experiment (currently only Fourier-discrimination)
- model describing the device used
- model describing the output
  - this one should include information defining the experiment and the device used so that the results files are self-contained

The examples below demonstrate suggested valid instances of the models written in YAML format, although the precise details of models may be changed at the discretion of the implementer.

**Experiment**
```yaml
type: fourier_discrimination,
qubits: 
- target: 0
  ancilla: 1
- target: 5
  ancilla: 2
angle: 
  start: 0.1
  stop: 0.2 
  number_of_steps: 2
method: postselection
number_of_shots: 5
```

**Device description**
```yaml
arn: arn:aws:braket:eu-west-2::device/qpu/oqc/Lucy
disable_qubit_rewiring: true
gateset: lucy
```

**Results**
```yaml
experiment:
  type: fourier_discrimination,
  qubits: 
  - target: 0
    ancilla: 1
  - target: 5
    ancilla: 2
  angle: 
    start: 0.1
    stop: 0.2
    number_of_steps: 2
  method: postselection
  number_of_shots: 5
device:
  arn: arn:aws:braket:eu-west-2::device/qpu/oqc/Lucy
  disable_qubit_rewiring: true
  gateset: lucy
results:
- target: 0
  ancilla: 1
  measurement_counts:
  - phi: 0.1
    counts:
      "11": 2
      "00": 3
  - phi: 0.2
    counts:
      "11": 1
      "10": 4
- target: 5
  ancilla: 2
  measurement_counts:
  - phi: 0.1
    counts:
      "00": 5
  - phi: 0.2
    counts:
      "01": 1
      "10": 4
```
